mqtt:
  broker: 8.156.78.153:1883
  client_id: cp
  client_password: cp123456
  topic: sensor/data

gin:
  ip: 127.0.0.1
  port: 8080
  jwt_secret: group_nine_is_most_nb_666

server:
  path: C:\Users\31389\Desktop\group-ten-server

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=True&loc=Local

room_mapping:
  room1: enviroment1
  room2: enviroment2
  room3: enviroment3
  room4: enviroment4