mqtt:
  broker: 8.156.78.153:1883
  client_id: cp

gin:
  ip: 127.0.0.1
  port: 8080
  jwt_secret: group_nine_is_most_nb_666

server:
  path: C:\Users\31389\Desktop\group-ten-server

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=True&loc=Local